language: node_js
node_js:
  - "8"
install:
  - npm i
script:
  - npm run build
  - npm run test
after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
